[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[build]
  command = "npm install && npx prisma generate && npm run build"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
  