name: Create .env file

on: [push, pull_request]

permissions:
  contents: read
  actions: read

jobs:
  create-env:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Retrieve variables
        run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/actions/variables?per_page=100

      - name: Run create_env script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Add this line
        run: |
          #!/bin/bash
  
          create_env () {
            gh variable list | grep DEVELOPMENT_ENV_FILE | tr ';' '\n' | sed -e "s/DEVELOPMENT_ENV_FILE //; s/[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}T[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}Z//g" | grep "\S" > .env
            echo "$(tput setaf 2)ENV file was created!$(tput sgr0)"
          }
  
          if [ "$CI" == "true" ]; then
            create_env
          else
            if command -v gh &>/dev/null; then
              create_env
            else
              echo "$(tput setaf 1)Github Cli could not be found$(tput sgr0)"
              echo "Please install: https://cli.github.com/"
            fi
          fi
